var ogloszeniaNaglowek = '5 NIEDZIELA WIELKANOCNA A - 3.05.2026 R.';
var ogloszenia = [
 
' DO ŚWIĘCEŃ DIAKONATU PRZYGOTOWUJE SIĘ KS. AKOLITA ADAM EDWARD NAPIERALSKI. KTO WIEDZIAŁBY O ZAISTNIAŁYCH PRZESZKODACH W TYCH ŚWIĘCENIACH POWINIEN POWIADOMIĆ URZĄD PARAFIALNYCH. KS. AKOLITĘ OBEJMUJEMY NASZYMI MODLITWAMI.',
' ZAPRASZAMY NA NABOŻEŃSTWA MAJOW PO MSZY O 18.00. ',
' DZIŚ W NIEDZIELĘ MSZA W INTENCJI RÓŻ RÓŻAŃCOWYCH I PARAFIAN O 8.30,PO NIEJ ADORACJA EUCHARYSTYCZNA, NABOŻEŃSTWO MAJOWE I ZMIANA TAJEMNIC',
' W NASTĘPNĄ NIEDZIELĘ NABOŻEŃSTWO MAJOWE PO MSZY O 11.00, A PO NIM SPOTKANIE DLA RODZICÓW I DZIECI PRZED I KOMUNIĄ. SPRZĄTANIE.',



];