var ogloszeniaNaglowek = 'NIEDZIELA ZESŁANIA DUCHA ŚW. A - 24.05.2026 R.';
var ogloszenia = [
 
' GRATULUJEMY KS. DIAKONOWI ADAMOWI PRZYJECIA ŚWIĘCEŃ DIAKONATU I PAMIĘTAJMY O MODLITWIE W PRZYGOTOWANIU DO KAPŁAŃSTWA. ',
' ZAPRASZAMY NA NABOŻEŃSTWA MAJOW PO MSZY O 18.00. A DZIŚ PO MSZY O 11.00 ',
' W NASTĘPNĄ NIEDZIELĘ UROCZYSTOŚĆ I KOMUNII DO  KTÓREJ PRZYGOTOWUJE SIĘ 8 DZIECI. SPOWIEDŹ DLA DZIECI I ICH RODZIN W SOBOTĘ O 11.00.',
' ZAPRASZAM CZŁONKÓW RADAY PARAFIALNEJ NA SPOTKANIE DZIŚ O 15.00 NA PLEBANII.',
' W IMIENIU P. GRZEGORZA Z OSTRÓDY ZAPRASZAM NA PIELGRZYMKI 1. Do Medjugorie w terminie 27.06 – 04.07.2026
Koszt wyjazdu: 1100 zł i 280 euro,do Włoch – rejon Apulii w terminie 09-19.07.2026,Koszt: 1400 zł i 800 euro i do Hiszpannii i Portugalii (Fatima i Santiago de Compostella) w dniach 22-29.09.26 w cenie 2400 zł i 790 euro. Informacje na tablicy odłoszeń.',
',


];