var ogloszeniaNaglowek = 'NIEDZIELA ODPUSTOWA A - 7.06.2026 R.';
var ogloszenia = [
' DZIŚ UROCZYSTOŚCI ODPOSTOWE. DZIĘKUJĘ ZA PRZYGOTOWANIE. SZCZEGÓLNIE DZIĘKUJEMY SIOSTROM KATARZYNKOM, NASZEJ SIOSTRZE IWONIE ZA POSŁUGĘ I WSZELKĄ POMOC. PRZY KAPLICY 14 MOŻNA ZAMÓWIĆ INTENCJE MSZALNE. W HERBACIARNI MOŻNA ZUKUPIĆ ZUPĘ LUB CIASTKO. ',
' ZAPRASZAMY NA NABOŻEŃSTWA CZERWCOWE PO MSZY O 18.00 ',
' DZIŚ W NIEDZIELĘ UROCZYSTOŚCI ODPUSTOWE. O 8.30 - MSZA Z KAZANIEM W INTENCJI RÓŻ RÓŻAŃCOWYCH I PARAFIAN, PO NIEJ POCZĄTEK ADORACJI EUCHARYSTYCZNEJ I ZMIANA TAJEMNIC, O 10.00 DROGA KRZYŻOWA, O 11.00- RÓŻĄNIEC, O 12.00 - PROCESJA I SUMA ODPUSTOWA - PRZEWODNICZY KS. INF. DR ADOLF SETLAK. PROSIMY O POMOC W PRZYGOTOWANIU UROCZYSTOŚCI OSP, UDZIAŁ W PROCESJI I O DARY NA STÓŁ ODPUSTOWY..',
' GRATULUJEMY DZIECIOM PRZYJĘCIA I SPOWIEDZI I I KOMUNII. ',
' ZAPRASZAMY NA NABOŻEŃSTWO MAJOW O 11.00, A OD JUTRA NA NABOŻEŃSTWA CZERWCOWE PO MSZY O 18.00 ',
' W CZWARTEK BOŻE CIAŁO - UROCZYSTOŚĆ NAJŚWIĘTSZEGO CIAŁA I KRWI PAŃSKIEJ. MSZA Z PROCESJĄ O 11.00. PROSZĘ O PRZYGOTOWANIE KAPLIC, ZADBANIE O BRZÓZKI PRZY NICH O UDZIAŁ W PROCESJI DZIECI, DOROSŁYCH A SZCZEGÓLNIE OSP. W PIŚTEK JEST DYSPENSA OD POSTU.',
' W NASTĘPNĄ NIEDZIELĘ UROCZYSTOŚCI ODPUSTOWE. O 8.30 - MSZA Z KAZANIEM W INTENCJI RÓŻ RÓŻAŃCOWYCH I PARAFIAN, PO NIEJ POCZĄTEK ADORACJI EUCHARYSTYCZNEJ I ZMIANA TAJEMNIC, O 10.00 DROGA KRZYŻOWA, O 11.00- RÓŻĄNIEC, O 12.00 - PROCESJA I SUMA ODPUSTOWA - PRZEWODNICZY KS. INF. DR ADOLF SETLAK. PROSIMY O POMOC W PRZYGOTOWANIU UROCZYSTOŚCI OSP, UDZIAŁ W PROCESJI I O DARY NA STÓŁ ODPUSTOWY..',
' W IMIENIU P. GRZEGORZA Z OSTRÓDY ZAPRASZAM NA PIELGRZYMKI 1. Do Medjugorie w terminie 27.06 – 04.07.2026, Koszt wyjazdu: 1100 zł i 280 euro,do Włoch – rejon Apulii w terminie 09-19.07.2026,Koszt: 1400 zł i 800 euro i do Hiszpannii i Portugalii (Fatima i Santiago de Compostella) w dniach 22-29.09.26 w cenie 2400 zł i 790 euro. Informacje na tablicy odłoszeń.',
];