var rekolekcjeNaglowek = 'REKOLEKCJE 2024';
var rekolekcje = [
    new Rekolekcje('21-23.03.2024 r.', 'REKOLEKCJE WIELKOPOSTNE W GŁOTOWIE. MSZE Z NAUKAMI O 11.00 I 18.00.'),
    new Rekolekcje('22-23.03.2024 r.', 'REKOLEKCJE STOWARZYSZENIA CIVITAS CHRISTIANA.'),
    new Rekolekcje('28-31.03.2024 r.', 'REKOLEKCJE TRIDUUM PASCHALNE DLA OSÓB DOROSŁYCH. W CZASIE REKOLEKCJI POGŁĘBIENIE PRZEŻYWANIA ŚWIĘTEGO TRIDUUM PASCHALNEGO. POCZĄTEK O 17.00 W WIELKI CZWARTEK, ZAKOŃCZENIE W NIEDZIELĘ OK.8.00.'),
    new Rekolekcje('23-26.05.2024 r.', 'DNI TRZEŹWOŚCI I RADOŚCI DLA OSÓB TRZEŹWIEJĄCYCH I WSPÓŁUZALEŻNIONYCH.'),
];
var zgloszenia = 'ZGŁOSZENIA NA WSZYSTKIE REKOLEKCJE: Ks. Marek Proszek, tel.606140178, e-mail mproszek@op.pl.';